// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqt9whed3zrSTMuqBPC_nNBA62PBDv7F8',
    appId: '1:690584510011:web:2659c437ab54b5a582c61e',
    messagingSenderId: '690584510011',
    projectId: 'doctorappointmentapp-a61ef',
    authDomain: 'doctorappointmentapp-a61ef.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-a61ef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9bWMjoS6SV6Hp7S8IqFOM6LfLV6rMbE',
    appId: '1:690584510011:android:bb49a39dd398055b82c61e',
    messagingSenderId: '690584510011',
    projectId: 'doctorappointmentapp-a61ef',
    storageBucket: 'doctorappointmentapp-a61ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv8SJmnOscNfRBGH5gxpSIFG_Uu_Eg90Q',
    appId: '1:690584510011:ios:6061ecbca987f2c582c61e',
    messagingSenderId: '690584510011',
    projectId: 'doctorappointmentapp-a61ef',
    storageBucket: 'doctorappointmentapp-a61ef.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv8SJmnOscNfRBGH5gxpSIFG_Uu_Eg90Q',
    appId: '1:690584510011:ios:6061ecbca987f2c582c61e',
    messagingSenderId: '690584510011',
    projectId: 'doctorappointmentapp-a61ef',
    storageBucket: 'doctorappointmentapp-a61ef.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqt9whed3zrSTMuqBPC_nNBA62PBDv7F8',
    appId: '1:690584510011:web:dcd56b754c628d3982c61e',
    messagingSenderId: '690584510011',
    projectId: 'doctorappointmentapp-a61ef',
    authDomain: 'doctorappointmentapp-a61ef.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-a61ef.firebasestorage.app',
  );

}